server:
  port: 8085

spring:
  application:
    name: pharmacy-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacy_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update